
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team01-s24-5pm-5
owner: ucsb-cs156-s24
repo_name: team01-s24-5pm-5
pull_requests: [{"author":{"id":"MDQ6VXNlcjM4MzkzMjM5","is_bot":false,"login":"tejasvissa813","name":""},"headRefName":"Tejas-TidesController","number":31,"title":"Tejas tides controller","url":"https://github.com/ucsb-cs156-s24/team01-s24-5pm-5/pull/31"},{"author":{"id":"MDQ6VXNlcjM4MzkzMjM5","is_bot":false,"login":"tejasvissa813","name":""},"headRefName":"Tejas-Tides","number":30,"title":"Added Tides Service and Tests","url":"https://github.com/ucsb-cs156-s24/team01-s24-5pm-5/pull/30"},{"author":{"id":"U_kgDOBdlAFQ","is_bot":false,"login":"maidang111","name":""},"headRefName":"Mai-PublicHolidayControllers","number":27,"title":"Added PublicHolidays Controller and Test","url":"https://github.com/ucsb-cs156-s24/team01-s24-5pm-5/pull/27"},{"author":{"id":"MDQ6VXNlcjM2MTM3NjU0","is_bot":false,"login":"Ononymous","name":"Gen Tamada"},"headRefName":"Gen-Location-Controller","number":23,"title":"Added Location Controller and Services","url":"https://github.com/ucsb-cs156-s24/team01-s24-5pm-5/pull/23"}]
