
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team01-s24-5pm-5
owner: ucsb-cs156-s24
repo_name: team01-s24-5pm-5
pull_requests: [{"author":{"id":"MDQ6VXNlcjM2MTM3NjU0","is_bot":false,"login":"Ononymous","name":"Gen Tamada"},"headRefName":"Gen-Location","number":19,"title":"Add Location Service and Test","url":"https://github.com/ucsb-cs156-s24/team01-s24-5pm-5/pull/19"},{"author":{"id":"MDQ6VXNlcjYxMzYwOTU1","is_bot":false,"login":"rileychou","name":"Riley Chou"},"headRefName":"Riley-University","number":18,"title":"Add University Service and Controller","url":"https://github.com/ucsb-cs156-s24/team01-s24-5pm-5/pull/18"}]
